-- =====================================================================
-- SCHEMA.SQL — ESTRUCTURA COMPLETA DE LA BASE DE DATOS SUMAJFLOW
-- =====================================================================
-- Generated by ChatGPT (based on RedGate original model)
-- =====================================================================

-- =====================================================
-- 1. CREACIÓN DE TABLAS
-- =====================================================

-- Table: almacen_comercializadora
CREATE TABLE almacen_comercializadora (
                                          id serial PRIMARY KEY,
                                          comercializadora_id int NOT NULL,
                                          nombre varchar(100) NOT NULL,
                                          capacidad_maxima decimal(12,6) NOT NULL,
                                          area decimal(12,6),
                                          departamento varchar(50),
                                          provincia varchar(100),
                                          municipio varchar(100),
                                          direccion varchar(250),
                                          latitud decimal(10,7),
                                          longitud decimal(10,7)
);

-- Table: almacen_ingenio
CREATE TABLE almacen_ingenio (
                                 id serial PRIMARY KEY,
                                 ingenio_minero_id int NOT NULL,
                                 nombre varchar(100) NOT NULL,
                                 capacidad_maxima decimal(12,6) NOT NULL,
                                 area decimal(12,6),
                                 departamento varchar(50),
                                 provincia varchar(100),
                                 municipio varchar(100),
                                 direccion varchar(250),
                                 latitud decimal(10,7),
                                 longitud decimal(10,7)
);

-- Table: asignacion_camion
CREATE TABLE asignacion_camion (
                                   id serial PRIMARY KEY,
                                   lotes_id int NOT NULL,
                                   transportista_id int NOT NULL,
                                   numero_camion int NOT NULL,
                                   estado varchar(50) DEFAULT 'asignado',
                                   fecha_asignacion timestamp DEFAULT now(),
                                   fecha_inicio timestamp,
                                   fecha_fin timestamp,
                                   peso_bruto decimal(12,2),
                                   peso_neto decimal(12,2),
                                   observaciones varchar(255)
);

-- Table: auditoria
CREATE TABLE auditoria (
                           id serial PRIMARY KEY,
                           usuarios_id int,
                           tipo_usuario varchar(50),
                           tabla_afectada varchar(100) NOT NULL,
                           accion varchar(20) NOT NULL,
                           registro_id int,
                           datos_anteriores jsonb,
                           datos_nuevos jsonb,
                           campos_modificados text,
                           ip_origen varchar(45),
                           user_agent text,
                           metodo_http varchar(10),
                           endpoint varchar(255),
                           fecha_operacion timestamp NOT NULL DEFAULT now(),
                           descripcion text,
                           nivel_criticidad varchar(20) DEFAULT 'medio',
                           modulo varchar(50),
                           operacion_exitosa boolean DEFAULT true,
                           mensaje_error text
);

-- Table: auditoria_lotes
CREATE TABLE auditoria_lotes (
                                 id serial PRIMARY KEY,
                                 lote_id int NOT NULL,
                                 tipo_usuario varchar(50),
                                 estado_anterior varchar(50),
                                 estado_nuevo varchar(50) NOT NULL,
                                 accion varchar(50) NOT NULL,
                                 descripcion text,
                                 observaciones text,
                                 metadata jsonb,
                                 ip_origen varchar(45),
                                 fecha_registro timestamp NOT NULL DEFAULT now()
);

-- Table: balanza_comercializadora
CREATE TABLE balanza_comercializadora (
                                          id serial PRIMARY KEY,
                                          comercializadora_id int NOT NULL,
                                          nombre varchar(100) NOT NULL,
                                          marca varchar(50) NOT NULL,
                                          modelo varchar(50) NOT NULL,
                                          numero_serie varchar(100) NOT NULL,
                                          capacidad_maxima decimal(12,3) NOT NULL,
                                          precision_minima decimal(8,3) NOT NULL,
                                          fecha_ultima_calibracion date NOT NULL,
                                          fecha_proxima_calibracion date NOT NULL,
                                          departamento varchar(50),
                                          provincia varchar(100),
                                          municipio varchar(100),
                                          direccion varchar(250),
                                          latitud decimal(10,7),
                                          longitud decimal(10,7)
);

-- Table: balanza_cooperativa
CREATE TABLE balanza_cooperativa (
                                     id serial PRIMARY KEY,
                                     cooperativa_id int NOT NULL,
                                     nombre varchar(100) NOT NULL,
                                     marca varchar(50) NOT NULL,
                                     modelo varchar(50) NOT NULL,
                                     numero_serie varchar(100) NOT NULL,
                                     capacidad_maxima decimal(12,3) NOT NULL,
                                     precision_minima decimal(8,3) NOT NULL,
                                     fecha_ultima_calibracion date NOT NULL,
                                     fecha_proxima_calibracion date NOT NULL,
                                     departamento varchar(50),
                                     provincia varchar(100),
                                     municipio varchar(100),
                                     direccion varchar(250),
                                     latitud decimal(10,7),
                                     longitud decimal(10,7)
);

-- Table: balanza_ingenio
CREATE TABLE balanza_ingenio (
                                 id serial PRIMARY KEY,
                                 ingenio_minero_id int NOT NULL,
                                 nombre varchar(100) NOT NULL,
                                 marca varchar(50) NOT NULL,
                                 modelo varchar(50) NOT NULL,
                                 numero_serie varchar(100) NOT NULL,
                                 capacidad_maxima decimal(12,3) NOT NULL,
                                 precision_minima decimal(8,3) NOT NULL,
                                 fecha_ultima_calibracion date NOT NULL,
                                 fecha_proxima_calibracion date NOT NULL,
                                 departamento varchar(50),
                                 provincia varchar(100),
                                 municipio varchar(100),
                                 direccion varchar(250),
                                 latitud decimal(10,7),
                                 longitud decimal(10,7)
);

-- Table: comercializadora
CREATE TABLE comercializadora (
                                  id serial PRIMARY KEY,
                                  razon_social varchar(100) NOT NULL,
                                  NIT varchar(50) NOT NULL,
                                  NIM int NOT NULL,
                                  correo_contacto varchar(50) NOT NULL,
                                  numero_telefono_fijo varchar(50),
                                  numero_telefono_movil varchar(50),
                                  departamento varchar(50) NOT NULL,
                                  provincia varchar(100) NOT NULL,
                                  municipio varchar(100) NOT NULL,
                                  direccion varchar(250) NOT NULL,
                                  latitud decimal(10,7),
                                  longitud decimal(10,7),
                                  usuarios_id int NOT NULL
);

-- Table: concentrado
CREATE TABLE concentrado (
                             id serial PRIMARY KEY,
                             codigo_concentrado varchar(50) NOT NULL,
                             ingenio_minero_id int NOT NULL,
                             lote_origen_id int,
                             socio_propietario_id int,
                             peso_inicial decimal(12,2) NOT NULL,
                             peso_final decimal(12,2),
                             merma decimal(12,2),
                             mineral_principal varchar(50),
                             estado varchar(50) DEFAULT 'creado',
                             fecha_inicio timestamp,
                             fecha_fin timestamp
);

-- Table: cooperativa
CREATE TABLE cooperativa (
                             id serial PRIMARY KEY,
                             razon_social varchar(100) NOT NULL,
                             NIT varchar(50) NOT NULL,
                             NIM int NOT NULL,
                             correo_contacto varchar(50) NOT NULL,
                             numero_telefono_fijo varchar(50),
                             numero_telefono_movil varchar(50),
                             departamento varchar(50) NOT NULL,
                             provincia varchar(100) NOT NULL,
                             municipio varchar(100) NOT NULL,
                             direccion varchar(250) NOT NULL,
                             latitud decimal(10,7),
                             longitud decimal(10,7),
                             usuarios_id int NOT NULL
);

-- Table: cooperativa_socio
CREATE TABLE cooperativa_socio (
                                   id serial PRIMARY KEY,
                                   cooperativa_id int NOT NULL,
                                   socio_id int NOT NULL,
                                   fecha_afiliacion date NOT NULL,
                                   estado varchar(50) DEFAULT 'pendiente',
                                   observaciones varchar(255)
);

-- Table: ingenio_minero
CREATE TABLE ingenio_minero (
                                id serial PRIMARY KEY,
                                razon_social varchar(100) NOT NULL,
                                NIT varchar(50) NOT NULL,
                                NIM int NOT NULL,
                                correo_contacto varchar(50) NOT NULL,
                                numero_telefono_fijo varchar(50),
                                numero_telefono_movil varchar(50),
                                departamento varchar(50) NOT NULL,
                                provincia varchar(100) NOT NULL,
                                municipio varchar(100) NOT NULL,
                                direccion varchar(250) NOT NULL,
                                latitud decimal(10,7),
                                longitud decimal(10,7),
                                usuarios_id int NOT NULL
);

-- Table: liquidacion
CREATE TABLE liquidacion (
                             id serial PRIMARY KEY,
                             lote_id int,
                             socio_id int NOT NULL,
                             tipo_liquidacion varchar(50) NOT NULL,
                             fecha_liquidacion date NOT NULL,
                             moneda varchar(10) DEFAULT 'bob',
                             peso_liquidado decimal(12,2),
                             valor_bruto decimal(15,2),
                             valor_neto decimal(15,2),
                             estado varchar(50) DEFAULT 'borrador'
);

-- Table: liquidacion_cotizacion
CREATE TABLE liquidacion_cotizacion (
                                        id serial PRIMARY KEY,
                                        liquidacion_id int NOT NULL,
                                        mineral varchar(50),
                                        cotizacion_usd decimal(15,2),
                                        unidad varchar(50)
);

-- Table: liquidacion_deduccion
CREATE TABLE liquidacion_deduccion (
                                       id serial PRIMARY KEY,
                                       liquidacion_id int NOT NULL,
                                       concepto varchar(100),
                                       monto decimal(15,2),
                                       porcentaje decimal(5,2),
                                       tipo_deduccion varchar(50) NOT NULL
);

-- Table: lote_comercializadora
CREATE TABLE lote_comercializadora (
                                       id serial PRIMARY KEY,
                                       comercializadora_id int NOT NULL,
                                       lotes_id int NOT NULL,
                                       estado varchar(50) DEFAULT 'pendiente',
                                       fecha_aprobacion timestamp,
                                       observaciones text
);

-- Table: lote_concentrado_relacion
CREATE TABLE lote_concentrado_relacion (
                                           id serial PRIMARY KEY,
                                           lote_complejo_id int NOT NULL,
                                           concentrado_id int NOT NULL,
                                           fecha_creacion timestamp DEFAULT now(),
                                           peso_entrada decimal(12,2) NOT NULL,
                                           peso_salida decimal(12,2),
                                           porcentaje_recuperacion decimal(5,2)
);

-- Table: lote_ingenio
CREATE TABLE lote_ingenio (
                              id serial PRIMARY KEY,
                              ingenio_minero_id int NOT NULL,
                              lotes_id int NOT NULL,
                              estado varchar(50) DEFAULT 'pendiente',
                              fecha_aprobacion timestamp,
                              observaciones text
);

-- Table: lote_minerales
CREATE TABLE lote_minerales (
                                id serial PRIMARY KEY,
                                lotes_id int NOT NULL,
                                minerales_id int NOT NULL
);

-- Table: lote_proceso_planta
CREATE TABLE lote_proceso_planta (
                                     id serial PRIMARY KEY,
                                     lote_id int NOT NULL,
                                     proceso_id int NOT NULL,
                                     orden int NOT NULL,
                                     estado varchar(50) DEFAULT 'pendiente',
                                     fecha_inicio timestamp,
                                     fecha_fin timestamp,
                                     observaciones text
);

-- Table: lotes
CREATE TABLE lotes (
                       id serial PRIMARY KEY,
                       minas_id int NOT NULL,
                       camiones_solicitados int NOT NULL,
                       tipo_operacion varchar(50) NOT NULL,
                       tipo_mineral varchar(50) NOT NULL,
                       estado varchar(50) NOT NULL,
                       fecha_creacion timestamp DEFAULT now(),
                       fecha_aprobacion_cooperativa timestamp,
                       fecha_aprobacion_destino timestamp,
                       fecha_inicio_transporte timestamp,
                       fecha_fin_transporte timestamp,
                       peso_total_estimado decimal(12,2),
                       peso_total_real decimal(12,2),
                       observaciones text
);

-- Table: minas
CREATE TABLE minas (
                       id serial PRIMARY KEY,
                       nombre varchar(100) NOT NULL,
                       foto_url varchar(200),
                       latitud decimal(10,7) NOT NULL,
                       longitud decimal(10,7) NOT NULL,
                       estado varchar(20) NOT NULL DEFAULT 'activo',
                       socio_id int NOT NULL,
                       sectores_id int NOT NULL
);

-- Table: minerales
CREATE TABLE minerales (
                           id serial PRIMARY KEY,
                           nombre varchar(100) NOT NULL,
                           nomenclatura varchar(50) NOT NULL
);

-- Table: notificaciones
CREATE TABLE notificaciones (
                                id serial PRIMARY KEY,
                                usuarios_id int NOT NULL,
                                tipo varchar(20) NOT NULL,
                                titulo varchar(200) NOT NULL,
                                mensaje text NOT NULL,
                                leido boolean NOT NULL DEFAULT false,
                                metadata jsonb,
                                fecha_creacion timestamp NOT NULL DEFAULT now(),
                                fecha_lectura timestamp
);

-- Table: persona
CREATE TABLE persona (
                         id serial PRIMARY KEY,
                         nombres varchar(100) NOT NULL,
                         primer_apellido varchar(50) NOT NULL,
                         segundo_apellido varchar(50),
                         ci varchar(50) NOT NULL,
                         fecha_nacimiento date NOT NULL,
                         numero_celular varchar(50),
                         genero varchar(20),
                         nacionalidad varchar(50),
                         departamento varchar(50),
                         provincia varchar(100),
                         municipio varchar(100),
                         direccion varchar(250),
                         latitud decimal(10,7),
                         longitud decimal(10,7),
                         usuarios_id int NOT NULL
);

-- Table: pesajes
CREATE TABLE pesajes (
                         id serial PRIMARY KEY,
                         tipo_pesaje varchar(50) NOT NULL,
                         peso_bruto decimal(12,2) NOT NULL,
                         peso_tara decimal(12,2) NOT NULL,
                         peso_neto decimal(12,2),
                         fecha_pesaje timestamp DEFAULT now(),
                         observaciones varchar(255),
                         asignacion_camion_id int NOT NULL
);

-- Table: planta
CREATE TABLE planta (
                        id serial PRIMARY KEY,
                        ingenio_minero_id int NOT NULL,
                        cupo_minimo decimal(12,6) NOT NULL,
                        capacidad_procesamiento decimal(12,6) NOT NULL,
                        costo_procesamiento decimal(12,6) NOT NULL,
                        licencia_ambiental_url varchar(200),
                        departamento varchar(50),
                        provincia varchar(100),
                        municipio varchar(100),
                        direccion varchar(250),
                        latitud decimal(10,7),
                        longitud decimal(10,7)
);

-- Table: planta_minerales
CREATE TABLE planta_minerales (
                                  id serial PRIMARY KEY,
                                  minerales_id int NOT NULL,
                                  planta_id int NOT NULL
);

-- Table: procesos
CREATE TABLE procesos (
                          id serial PRIMARY KEY,
                          nombre varchar(50) NOT NULL
);

-- Table: procesos_planta
CREATE TABLE procesos_planta (
                                 id serial PRIMARY KEY,
                                 planta_id int NOT NULL,
                                 procesos_id int NOT NULL,
                                 orden int NOT NULL
);

-- Table: reporte_quimico
CREATE TABLE reporte_quimico (
                                 id serial PRIMARY KEY,
                                 numero_reporte varchar(100) NOT NULL,
                                 laboratorio varchar(100),
                                 fecha_analisis date NOT NULL,
                                 ley_ag decimal(8,4),
                                 ley_pb decimal(8,4),
                                 ley_zn decimal(8,4),
                                 humedad decimal(5,2),
                                 tipo_analisis varchar(50),
                                 url_pdf varchar(200),
                                 lote_id int
);

-- Table: sectores
CREATE TABLE sectores (
                          id serial PRIMARY KEY,
                          nombre varchar(100) NOT NULL,
                          color varchar(10),
                          cooperativa_id int NOT NULL,
                          estado varchar(50) DEFAULT 'activo'
);

-- Table: sectores_coordenadas
CREATE TABLE sectores_coordenadas (
                                      id serial PRIMARY KEY,
                                      orden int NOT NULL,
                                      sectores_id int NOT NULL,
                                      latitud decimal(10,7) NOT NULL,
                                      longitud decimal(10,7) NOT NULL
);

-- Table: socio
CREATE TABLE socio (
                       id serial PRIMARY KEY,
                       fecha_envio timestamp NOT NULL,
                       estado varchar(100) NOT NULL,
                       carnet_afiliacion_url varchar(200),
                       carnet_identidad_url varchar(200),
                       usuarios_id int NOT NULL
);

-- Table: tipo_usuario
CREATE TABLE tipo_usuario (
                              id serial PRIMARY KEY,
                              tipo_usuario varchar(50) NOT NULL
);

-- Table: transportista
CREATE TABLE transportista (
                               id serial PRIMARY KEY,
                               usuarios_id int NOT NULL,
                               ci varchar(20) NOT NULL,
                               licencia_conducir varchar(50) NOT NULL,
                               categoria_licencia varchar(10) NOT NULL,
                               fecha_vencimiento_licencia date NOT NULL,
                               placa_vehiculo varchar(20) NOT NULL,
                               marca_vehiculo varchar(50),
                               modelo_vehiculo varchar(50),
                               color_vehiculo varchar(30),
                               peso_tara decimal(12,2),
                               capacidad_carga decimal(12,2),
                               estado varchar(50) DEFAULT 'pendiente',
                               fecha_aprobacion timestamp,
                               viajes_completados int DEFAULT 0,
                               calificacion_promedio decimal(3,2) DEFAULT 0
);

-- Table: usuarios
CREATE TABLE usuarios (
                          id serial PRIMARY KEY,
                          correo varchar(50) NOT NULL,
                          contrasena varchar(250) NOT NULL,
                          tipo_usuario_id int NOT NULL
);

-- =====================================================
-- 2. FOREIGN KEYS
-- (todas las llaves foráneas reordenadas)
-- =====================================================

ALTER TABLE usuarios ADD CONSTRAINT FK_0 FOREIGN KEY (tipo_usuario_id) REFERENCES tipo_usuario(id);
ALTER TABLE persona ADD CONSTRAINT FK_1 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE cooperativa ADD CONSTRAINT FK_2 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE socio ADD CONSTRAINT FK_3 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE cooperativa_socio ADD CONSTRAINT FK_4 FOREIGN KEY (cooperativa_id) REFERENCES cooperativa(id);
ALTER TABLE cooperativa_socio ADD CONSTRAINT FK_5 FOREIGN KEY (socio_id) REFERENCES socio(id);
ALTER TABLE ingenio_minero ADD CONSTRAINT FK_6 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE comercializadora ADD CONSTRAINT FK_7 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE transportista ADD CONSTRAINT FK_8 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE sectores ADD CONSTRAINT FK_9 FOREIGN KEY (cooperativa_id) REFERENCES cooperativa(id);
ALTER TABLE sectores_coordenadas ADD CONSTRAINT FK_10 FOREIGN KEY (sectores_id) REFERENCES sectores(id);
ALTER TABLE minas ADD CONSTRAINT FK_11 FOREIGN KEY (sectores_id) REFERENCES sectores(id);
ALTER TABLE minas ADD CONSTRAINT FK_12 FOREIGN KEY (socio_id) REFERENCES socio(id);
ALTER TABLE almacen_ingenio ADD CONSTRAINT FK_13 FOREIGN KEY (ingenio_minero_id) REFERENCES ingenio_minero(id);
ALTER TABLE almacen_comercializadora ADD CONSTRAINT FK_14 FOREIGN KEY (comercializadora_id) REFERENCES comercializadora(id);
ALTER TABLE balanza_cooperativa ADD CONSTRAINT FK_15 FOREIGN KEY (cooperativa_id) REFERENCES cooperativa(id);
ALTER TABLE balanza_ingenio ADD CONSTRAINT FK_16 FOREIGN KEY (ingenio_minero_id) REFERENCES ingenio_minero(id);
ALTER TABLE balanza_comercializadora ADD CONSTRAINT FK_17 FOREIGN KEY (comercializadora_id) REFERENCES comercializadora(id);
ALTER TABLE planta ADD CONSTRAINT FK_18 FOREIGN KEY (ingenio_minero_id) REFERENCES ingenio_minero(id);
ALTER TABLE planta_minerales ADD CONSTRAINT FK_19 FOREIGN KEY (planta_id) REFERENCES planta(id);
ALTER TABLE planta_minerales ADD CONSTRAINT FK_20 FOREIGN KEY (minerales_id) REFERENCES minerales(id);
ALTER TABLE procesos_planta ADD CONSTRAINT FK_21 FOREIGN KEY (planta_id) REFERENCES planta(id);
ALTER TABLE procesos_planta ADD CONSTRAINT FK_22 FOREIGN KEY (procesos_id) REFERENCES procesos(id);
ALTER TABLE lotes ADD CONSTRAINT FK_23 FOREIGN KEY (minas_id) REFERENCES minas(id);
ALTER TABLE lote_ingenio ADD CONSTRAINT FK_24 FOREIGN KEY (ingenio_minero_id) REFERENCES ingenio_minero(id);
ALTER TABLE lote_ingenio ADD CONSTRAINT FK_25 FOREIGN KEY (lotes_id) REFERENCES lotes(id);
ALTER TABLE lote_comercializadora ADD CONSTRAINT FK_26 FOREIGN KEY (comercializadora_id) REFERENCES comercializadora(id);
ALTER TABLE lote_comercializadora ADD CONSTRAINT FK_27 FOREIGN KEY (lotes_id) REFERENCES lotes(id);
ALTER TABLE lote_minerales ADD CONSTRAINT FK_28 FOREIGN KEY (lotes_id) REFERENCES lotes(id);
ALTER TABLE lote_minerales ADD CONSTRAINT FK_29 FOREIGN KEY (minerales_id) REFERENCES minerales(id);
ALTER TABLE lote_proceso_planta ADD CONSTRAINT FK_30 FOREIGN KEY (lote_id) REFERENCES lotes(id);
ALTER TABLE lote_proceso_planta ADD CONSTRAINT FK_31 FOREIGN KEY (proceso_id) REFERENCES procesos(id);
ALTER TABLE asignacion_camion ADD CONSTRAINT FK_33 FOREIGN KEY (lotes_id) REFERENCES lotes(id);
ALTER TABLE asignacion_camion ADD CONSTRAINT FK_34 FOREIGN KEY (transportista_id) REFERENCES transportista(id);
ALTER TABLE pesajes ADD CONSTRAINT FK_35 FOREIGN KEY (asignacion_camion_id) REFERENCES asignacion_camion(id);
ALTER TABLE concentrado ADD CONSTRAINT FK_36 FOREIGN KEY (ingenio_minero_id) REFERENCES ingenio_minero(id);
ALTER TABLE concentrado ADD CONSTRAINT FK_37 FOREIGN KEY (lote_origen_id) REFERENCES lotes(id);
ALTER TABLE concentrado ADD CONSTRAINT FK_38 FOREIGN KEY (socio_propietario_id) REFERENCES socio(id);
ALTER TABLE lote_concentrado_relacion ADD CONSTRAINT FK_39 FOREIGN KEY (lote_complejo_id) REFERENCES lotes(id);
ALTER TABLE lote_concentrado_relacion ADD CONSTRAINT FK_40 FOREIGN KEY (concentrado_id) REFERENCES concentrado(id);
ALTER TABLE reporte_quimico ADD CONSTRAINT FK_42 FOREIGN KEY (lote_id) REFERENCES lotes(id);
ALTER TABLE liquidacion ADD CONSTRAINT FK_44 FOREIGN KEY (lote_id) REFERENCES lotes(id);
ALTER TABLE liquidacion ADD CONSTRAINT FK_45 FOREIGN KEY (socio_id) REFERENCES socio(id);
ALTER TABLE liquidacion_cotizacion ADD CONSTRAINT FK_46 FOREIGN KEY (liquidacion_id) REFERENCES liquidacion(id);
ALTER TABLE liquidacion_deduccion ADD CONSTRAINT FK_47 FOREIGN KEY (liquidacion_id) REFERENCES liquidacion(id);
ALTER TABLE auditoria ADD CONSTRAINT FK_48 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);
ALTER TABLE auditoria_lotes ADD CONSTRAINT FK_49 FOREIGN KEY (lote_id) REFERENCES lotes(id);
ALTER TABLE notificaciones ADD CONSTRAINT FK_51 FOREIGN KEY (usuarios_id) REFERENCES usuarios(id);

-- =====================================================
-- 3. FUNCIONES DE AUDITORÍA
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_created_at_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.created_at =_
